spring.application.name=InvetoryManagement
spring.datasource.url=jdbc:postgresql://db.metrpmrbkbdrfhmszpyb.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=makoko.Coder#001


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=norbertwitness570@gmail.com
spring.mail.password=btdxlnsmlafguqtb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.connectiontimeout=5000